apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aerospace-logistics-tracking
  namespace: argocd
  # Finalizers ensure that if you delete this Argo App, it cleanly tears down the resources inside the cluster too
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # REPO CONFIGURATION
    repoURL: 'https://github.com/Alice-tech-node/Ticket-001-Local-Kubernetes-Environment.git'
    targetRevision: main
    path: 'My Tracking App' 
    
    # This allows Argo CD to recursively scan and deploy all subdirectories (backend, frontend, etc.)
    directory:
      recurse: true

  destination:
    # TARGET CLUSTER CONFIGURATION
    server: 'https://kubernetes.default.svc'
    namespace: asl-dev # Deploys the entire stack into a clean dedicated namespace

  syncPolicy:
    # AUTOMATION CONFIGURATION
    automated:
      prune: true     # Automatically deletes resources in K8s if you delete their YAML files from Git
      selfHeal: true  # Prevents configuration drift (if someone manually edits a live pod, Argo overrides it back to Git spec)
    syncOptions:
      - CreateNamespace=true # Tells Argo to create the 'asl-dev' namespace if it doesn't exist yet
